{% set version = "3.6.1" %}

package:
  name: typing
  version: {{ version }}

source:
  fn: typing-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/typing/typing-{{ version }}.tar.gz
  sha256: c36dec260238e7464213dcd50d4b5ef63a507972f5780652e835d0228d0edace

build:
    number: 0
    script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - typing

about:
  home: https://docs.python.org/3.5/library/typing.html
  license: PSF
  license_file: LICENSE
  summary: 'Type Hints for Python - backport for Python<3.5'

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
