{% set version = "3.7.4" %}

package:
  name: typing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/typing/typing-{{ version }}.tar.gz
  sha256: 53765ec4f83a2b720214727e319607879fec4acde22c4fbb54fa2604e79e44ce

build:
  number: 0
  skip: True  # [py>=36]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - typing

about:
  home: https://docs.python.org/3.5/library/typing.html
  license: PSF
  license_file: LICENSE
  summary: 'Type Hints for Python - backport for Python<3.5'

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
