{% set version = "3.7.4.2" %}

package:
  name: typing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/typing/typing-{{ version }}.tar.gz
  sha256: 6f6f3553709d2234e412092e5daa93aaaaa42ea1854505442280b39f9311707f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [py==27]
  script: echo "dummy package for python 3"  # [py> 27]

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - typing

about:
  home: https://docs.python.org/3.5/library/typing.html
  license: PSF
  license_file: LICENSE
  summary: Type Hints for Python - backport for Python<3.5

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
