{% set version = "3.6.2" %}

package:
  name: typing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/typing/typing-{{ version }}.tar.gz
  sha256: d514bd84b284dd3e844f0305ac07511f097e325171f6cc4a20878d11ad771849

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - typing

about:
  home: https://docs.python.org/3.5/library/typing.html
  license: PSF
  license_file: LICENSE
  summary: 'Type Hints for Python - backport for Python<3.5'
  
  description: |
    This is a backport of the standard library typing module to Python versions
    older than 3.5. Typing defines a standard notation for Python function and
    variable type annotations. The notation can be used for documenting code in
    a concise, standard format, and it has been designed to also be used by
    static and runtime type checkers, static analyzers, IDEs and other tools.

  doc_url: https://docs.python.org/3.5/library/typing.html
  dev_url: https://github.com/python/cpython/blob/3.5/Lib/typing.py
  doc_source_url: https://github.com/python/cpython/tree/3.5/Doc

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
