{% set version = "3.5.0.1" %}

package:
  name: typing
  version: {{ version }}

source:
  fn: typing-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/t/typing/typing-{{ version }}.tar.gz
  md5: dae3d560f98c8b236a64ef1c0f55273a

build:
    number: 0
    script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - typing

about:
  home: https://docs.python.org/3.5/library/typing.html
  license: Python Software Foundation License
  summary: 'Type Hints for Python - backport for Python<3.5'

extra:
  recipe-maintainers:
    - msarahan
